commandlog: false
webhook: ''

commands:
  borsenchant: true
  grindstone: true
  updatelore: true

enchantments:
  experience: true
  poison: true
  telekinesis: true
  veinminer: false # due to bug

plugins:
  anticombatlog: false
  consolecommand: false
  lifesteal: false

recipes:
  nether_star: false
  saddle: false
  shulker_box: false
  trident: false